version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker node image... 
      - cd ui         
      - docker build -t ui:latest .
      - docker tag ui:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ui:latest 
      - echo Building the Docker nginx image...  
      - cd ..
      - cd nginx        
      - docker build -t nginx:latest .
      - docker tag nginx:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nginx:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ui:latest
      - printf '[{"name":"ui","imageUri":"%s"}]' 637904357981.dkr.ecr.us-east-2.amazonaws.com/ui:latest > imagedefinitions.json
      - echo Pushing the Docker Nginx image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/nginx:latest
      - printf '[{"name":"uinginx","imageUri":"%s"}]' 637904357981.dkr.ecr.us-east-2.amazonaws.com/nginx:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
  files: imagedefinitions.json